spring:
  application:
    name: golden-harvest
  mvc:
    static-path-pattern: /files/** # 브라우저 요청 URL 패턴
  web:
    resources:
      static-locations: file:./uploads/  # 실제 파일 위치 (프로젝트 루트의 uploads 폴더)
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${AWS_MSK_URL}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: golden-harvest-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  datasource:
    url: jdbc:mariadb://${AMAZON_RDS}:3306/goldenharvest
    username: admin
    password: harvest123
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      maximum-pool-size: 8        # 동시에 "빌릴 수 있는" 최대 커넥션
      minimum-idle: 2             # 놀고 있어도 유지할 최소 커넥션
      connection-timeout: 30000   # 커넥션 얻기 최대 대기(ms)
      idle-timeout: 300000        # 유휴 커넥션 정리(ms)
      max-lifetime: 1800000       # 커넥션 최대 수명(ms) (RDS 권장값과 충돌 방지)
      leak-detection-threshold: 20000  # 20초 넘게 반납 안 하면 로그 경고
      pool-name: goldenharvest-hikari

  jpa:
    hibernate:
      ddl-auto: update #수정 금지
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

server:
  port: ${SERVER_PORT}

inventory:
  base-url: http://localhost:8088
